language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
script: npm run test:cover

after_script:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js